### ISSUE TITLE
Installing OpenCart again this time from a FreeBSD jail

### ISSUE THREAD

**Issue by prepstarr** [opencart/opencart#11325]
**What version of OpenCart are you reporting this for?**

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

Warning: require(/usr/local/www/apache24/data/system/storage/vendor/composer/../react/promise/src/functions_include.php): Failed to open stream: No such file or directory in /usr/local/www/apache24/data/system/storage/vendor/composer/autoload_real.php on line 69

Fatal error: Uncaught Error: Failed opening required '/usr/local/www/apache24/data/system/storage/vendor/composer/../react/promise/src/functions_include.php' (include_path='.:/usr/local/share/pear') in /usr/local/www/apache24/data/system/storage/vendor/composer/autoload_real.php:69 Stack trace: #0 /usr/local/www/apache24/data/system/storage/vendor/composer/autoload_real.php(59): composerRequirea8cb75283b86ff94542c6f1327c4ce59('ad155f8f1cf0d41...', '/usr/local/www/...') #1 /usr/local/www/apache24/data/system/storage/vendor/autoload.php(7): ComposerAutoloaderInita8cb75283b86ff94542c6f1327c4ce59::getLoader() #2 /usr/local/www/apache24/data/system/startup.php(71): require_once('/usr/local/www/...') #3 /usr/local/www/apache24/data/install/index.php(35): require_once('/usr/local/www/...') #4 {main} thrown in /usr/local/www/apache24/data/system/storage/vendor/composer/autoload_real.php on line 69

**To Reproduce**
https://hydroponique.shop

5. See error

**Expected behavior**

It was supposed to take me through a guided install of the program .

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

![image](https://user-images.githubusercontent.com/65930206/174219600-278cd881-d2e6-4348-a918-de813839eb51.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?

web server

 - Operating system
FreeBSD hydroponique.shop 13.1-RELEASE FreeBSD 13.1-RELEASE releng/13.1-n250148-fc952ac2212 GENERIC  amd64

I didn't upgrade it from the jail and raw sockets are still permitted so I have some issues that will need to be worked on...

 - PHP version
php -v 

PHP 8.0.18 (cli) (built: Apr 16 2022 07:30:49) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.18, Copyright (c) Zend Technologies

 - Apache version
root@hydroponique:/usr/local/www/apache24/data # httpd -v
Server version: Apache/2.4.53 (FreeBSD)
Server built:   unknown

 - Browser(s) tested with [e.g. chrome, safari - if applicable]

Edge - chrome based browser by Microsoft

**Additional context**

latest version of Open Cart for php80

**Comment by prepstarr** [comment]
the reason for the freebsd jail is so that I can maintain a working version of PHP, because I upgraded my php to the latest 8.1 and this is what caused the error in my previous working version of OpenCart. If I get an online running on php that works I want to stick to that version at the same time, I want some indepence on my server to allow me to run the version of PHP that I need.
