### ISSUE TITLE
SMTP mail configurations for opencart 3.0.8.0

### ISSUE THREAD

**Issue by mrtz16562** [opencart/opencart#11436]
**opencart 3.0.8.0**

Fatal error: Uncaught Exception: Error: Password not accepted from server! in /home2/mysoftstore/public_html/system/library/mail/smtp.php:241 Stack trace: #0 /home2/mysoftstore/public_html/system/library/mail/smtp.php(147): Mail\Smtp->handleReply(Resource id #9, 235, 'Error: Password...') #1 /home2/mysoftstore/public_html/system/library/mail.php(142): Mail\Smtp->send() #2 /home2/mysoftstore/public_html/catalog/controller/information/contact.php(25): Mail->send() #3 /home2/mysoftstore/ocartdata/storage/modification/system/engine/action.php(79): ControllerInformationContact->index() #4 /home2/mysoftstore/public_html/catalog/controller/startup/router.php(25): Action->execute(Object(Registry)) #5 /home2/mysoftstore/ocartdata/storage/modification/system/engine/action.php(79): ControllerStartupRouter->index() #6 /home2/mysoftstore/public_html/system/engine/router.php(67): Action->execute(Object(Registry)) #7 /home2/mysoftstore/public_html/system/engine/router.php(56): Router->execute(Object(Action)) #8 /home2/mysoftstore/public in /home2/mysoftstore/public_html/system/library/mail/smtp.php on line 241

**To Reproduce**
Happens when I send a message from the contact-us form for when an order is placed

**Expected behavior**
A message should be sent to the admin email address.

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Comment by mrtz16562** [comment]
AM using cpanel, can I solve this myself?
