### ISSUE TITLE
PHP Fatal error, when deleting language in admin (OC 2.3.0.2)

### ISSUE THREAD

**Issue by arnisjuraga** [opencart/opencart#4801]
Version: Latest OC 2.3.0.2 fresh install

To reproduce:

1. Install OC 2.3.0.2 // :+1: 
2. Create empty folder with new language code under admin/languages, e.g. "lv"
3. Go to System > Localisation > Languages
4. Install language.
5. Now, try to delete it - You will get PHP Fatal error, although language will be deleted:

~~~php
==> /home/www/example.com/oct2302/log/oct2302.example.com_error_log <==
PHP message: PHP Fatal error:  Uncaught exception 'Exception' with message 'Error: Table 'oct2302.oc_banner_image_description' doesn't exist
<br />Error No: 1146<br />DELETE FROM oc_banner_image_description WHERE language_id = '2'' 
in /home/www/example.com/oct2302/public_html/system/library/db/mysqli.php:40, 
referer: http://oct2302.example.com/admin/index.php?route=localisation/language&token=qm7P6NiWlXc1xqk8FC7a9AUVRoglxDyC
Stack trace:, referer: http://oct2302.example.com/admin/index.php?route=localisation/language&token=qm7P6NiWlXc1xqk8FC7a9AUVRoglxDyC
#0 /home/www/example.com/oct2302/public_html/system/library/db.php(16): DB\\MySQLi->query('DELETE FROM oc_...', Array), 
referer: http://oct2302.example.com/admin/index.php?route=localisation/language&token=qm7P6NiWlXc1xqk8FC7a9AUVRoglxDyC
#1 /home/www/example.com/oct2302/public_html/admin/model/localisation/language.php(222): DB->query('DELETE FROM oc_...'), 
referer: http://oct2302.example.com/admin/index.php?route=localisation/language&token=qm7P6NiWlXc1xqk8FC7a9AUVRoglxDyC
#2 [internal function]: ModelLocalisationLanguage->deleteLanguage('2'), 
referer: http://oct2302.example.com/admin/index.php?route=localisation/language&token=qm7P6NiWlXc1xqk8FC7a9AUVRoglxDyC
#3 /home/www/example.com/oct2302/public_html/system/engine/loader.php(178): call_user_func_array(Array, Array), 
referer: http://oct2302.example.com/admin/index.php?route=localisation/language&token=qm7P6NiWlXc1xqk8FC7a9AUVRoglxDyC
#4 [internal function]: Loader->{closure}(Array, Array), 
referer: http://oct2302.example.com/admin/index.php?route=localisation/language&token=qm7P6NiWlXc1xqk8FC7a9AUVRoglxDyC
#5 /home/www/example.com/oct2302/public_html/system/engine/proxy.php(25): call_user_func_array(Object(Closure), 
Array), referer: http://oct2302.example.com/admin/index.php?route=localisation/language&token=qm7P6NiWlXc1xqk8FC7a9AUVRoglxDyC
#6 /home/www/example.com/oct2302/public_html/admin/controller/localisation/language.php(88): Proxy->...,
referer: http://oct2302.example.com/admin/index.php?route=localisation/language&token=qm7P6NiWlXc1xqk8FC7a9AUVRoglxDyC

~~~

**Comment by arnisjuraga** [comment]
I believie, this one is fixed here?  #4722
