### ISSUE TITLE
Error updating OC to latest release

### ISSUE THREAD

**Issue by mehtaman** [opencart/opencart#5718]
`Fatal error: 
Uncaught Exception: 
Error: Could not load template adaptor ! in /home/u572407319/public_html/system/library/template.php:11 
Stack trace: #0 /home/u572407319/public_html/system/storage/modification/system/engine/loader.php(81): 

Template->__construct(NULL) #1 /home/u572407319/public_html/install/controller/common/header.php(14): Loader-

>view('common/header', Array) #2 /home/u572407319/public_html/system/storage/modification/system/engine/action.php(51): 

ControllerCommonHeader->index(Array) #3 /home/u572407319/public_html/system/storage/modification/system/engine/loader.php(24): Action-

>execute(Object(Registry), Array) #4 /home/u572407319/public_html/install/controller/upgrade/upgrade.php(28): Loader-

>controller('common/header') #5 /home/u572407319/public_html/system/storage/modification/system/engine/action.php(51): ControllerUpgradeUpgrade->index() 

#6 /home/u572407319/public_html/system/engine/router.php(34): Action->execute(Object(Registry)) 

#7 /home/u572407319/public_html/system/engine/router.php(29): Router in /home/u572407319/public_html/system/library/template.php on line 11`

**Comment by mehtaman** [comment]
Thanks I will give this a go now :+1:

**Comment by mehtaman** [comment]
That worked but then when I click continue the upgrade failed:
`SyntaxError: Unexpected token < in JSON at position 0 parsererror Warning: file() expects parameter 1 to be a valid path, resource given in /home/u572407319/public_html/install/model/upgrade/1009.php on line 161Warning: Invalid argument supplied for foreach() in /home/u572407319/public_html/install/model/upgrade/1009.php on line 163Warning: Invalid argument supplied for foreach() in /home/u572407319/public_html/install/model/upgrade/1009.php on line 174Warning: fopen() expects parameter 1 to be a valid path, resource given in /home/u572407319/public_html/install/model/upgrade/1009.php on line 183Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/u572407319/public_html/install/model/upgrade/1009.php on line 185Warning: fclose() expects parameter 1 to be resource, boolean given in /home/u572407319/public_html/install/model/upgrade/1009.php on line 187Warning: file() expects parameter 1 to be a valid path, resource given in /home/u572407319/public_html/install/model/upgrade/1009.php on line 199Warning: Invalid argument supplied for foreach() in /home/u572407319/public_html/install/model/upgrade/1009.php on line 203Warning: fopen() expects parameter 1 to be a valid path, resource given in /home/u572407319/public_html/install/model/upgrade/1009.php on line 219Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/u572407319/public_html/install/model/upgrade/1009.php on line 221Warning: fclose() expects parameter 1 to be resource, boolean given in /home/u572407319/public_html/install/model/upgrade/1009.php on line 223Warning: file() expects parameter 1 to be a valid path, resource given in /home/u572407319/public_html/install/model/upgrade/1009.php on line 161Warning: Invalid argument supplied for foreach() in /home/u572407319/public_html/install/model/upgrade/1009.php on line 163Warning: Invalid argument supplied for foreach() in /home/u572407319/public_html/install/model/upgrade/1009.php on line 174Warning: fopen() expects parameter 1 to be a valid path, resource given in /home/u572407319/public_html/install/model/upgrade/1009.php on line 183Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/u572407319/public_html/install/model/upgrade/1009.php on line 185Warning: fclose() expects parameter 1 to be resource, boolean given in /home/u572407319/public_html/install/model/upgrade/1009.php on line 187Warning: file() expects parameter 1 to be a valid path, resource given in /home/u572407319/public_html/install/model/upgrade/1009.php on line 199Warning: Invalid argument supplied for foreach() in /home/u572407319/public_html/install/model/upgrade/1009.php on line 203Warning: fopen() expects parameter 1 to be a valid path, resource given in /home/u572407319/public_html/install/model/upgrade/1009.php on line 219Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/u572407319/public_html/install/model/upgrade/1009.php on line 221Warning: fclose() expects parameter 1 to be resource, boolean given in /home/u572407319/public_html/install/model/upgrade/1009.php on line 223{"success":"Patch 1009 has been applied (10 of 10)","next":"index.php?route=upgrade\/upgrade\/next&step=11"}`

**Comment by mehtaman** [comment]
Still getting errors once the upgrade ran:



Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51

Notice: Use of undefined constant DIR_LOGS - assumed 'DIR_LOGS' in /home/u572407319/public_html/system/library/log.php on line 6
Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 59Notice: Use of undefined constant DIR_CACHE - assumed 'DIR_CACHE' in /home/u572407319/public_html/system/library/cache/file.php on line 9Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 59Notice: Use of undefined constant DIR_LOGS - assumed 'DIR_LOGS' in /home/u572407319/public_html/system/library/log.php on line 6Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 59Notice: Use of undefined constant DIR_LOGS - assumed 'DIR_LOGS' in /home/u572407319/public_html/system/library/log.php on line 6Notice: Use of undefined constant DIR_LOGS - assumed 'DIR_LOGS' in /home/u572407319/public_html/system/library/log.php on line 6Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 59Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 51Notice: Use of undefined constant DIR_MODIFICATION - assumed 'DIR_MODIFICATION' in /home/u572407319/public_html/system/startup.php on line 59Notice: Use of undefined constant DIR_CACHE - assumed 'DIR_CACHE' in /home/u572407319/public_html/system/library/cache/file.php on line 25Notice: Use of undefined constant DIR_CACHE - assumed 'DIR_CACHE' in /home/u572407319/public_html/system/library/cache/file.php on line 63Notice: Use of undefined constant DIR_CACHE - assumed 'DIR_CACHE' in /home/u572407319/public_html/system/library/cache/file.php on line 47Notice: Use of undefined constant DIR_CACHE - assumed 'DIR_CACHE' in /home/u572407319/public_html/system/library/cache/file.php on line 63

**Comment by mehtaman** [comment]
now my store page is asking to select a theme
when I did extensions to enable them i get an error

Notice: Undefined index: token in /home/u572407319/public_html/admin/controller/extension/captcha/google_captcha.php on line 56Notice: Undefined index: token in /home/u572407319/public_html/admin/controller/extension/captcha/google_captcha.php on line 61Notice: Undefined index: token in /home/u572407319/public_html/admin/controller/extension/captcha/google_captcha.php on line 66Notice: Undefined index: token in /home/u572407319/public_html/admin/controller/extension/captcha/google_captcha.php on line 69Notice: Undefined index: token in /home/u572407319/public_html/admin/controller/extension/captcha/google_captcha.php on line 71
Fatal error: Uncaught Twig_Error_Loader: Unable to find template "extension/captcha/google_captcha.twig" (looked into: /home/u572407319/public_html/admin/view/template). in /home/u572407319/public_html/system/library/template/Twig/Loader/Filesystem.php:215 Stack trace: #0 /home/u572407319/public_html/system/library/template/Twig/Loader/Filesystem.php(139): Twig_Loader_Filesystem->findTemplate('extension/captc...') #1 /home/u572407319/public_html/system/library/template/Twig/Environment.php(312): Twig_Loader_Filesystem->getCacheKey('extension/captc...') #2 /home/u572407319/public_html/system/library/template/Twig/Environment.php(378): Twig_Environment->getTemplateClass('extension/captc...', NULL) #3 /home/u572407319/public_html/system/library/template/twig.php(36): Twig_Environment->loadTemplate('extension/captc...') #4 /home/u572407319/public_html/system/library/template.php(20): Template\Twig->render('extension/captc...', NULL) #5 /home/u572407319/public_html/system/engine/loader.php(85): Template->render('extension/capt in /home/u572407319/public_html/system/library/template/Twig/Loader/Filesystem.php on line 215

**Comment by danielkerr** [comment]
u have mixed the old files with the new one. 

delete the file

/home/u572407319/public_html/admin/controller/extension/captcha/google_captcha.php

and any others that throw an error like this.

**Comment by ankit521** [comment]
Getting error while adding new Payment Method to OpenCart 3.x. Installation happened smoothly but while editing this payment method getting this error.  


Fatal error: Uncaught Twig_Error_Loader: Unable to find template "extension/payment/paytmtpl.twig" (looked into: C:/xampp/htdocs/oczest/upload/admin/view/template). in C:\xampp\htdocs\oczest\upload\system\library\template\Twig\Loader\Filesystem.php:215 Stack trace: #0 C:\xampp\htdocs\oczest\upload\system\library\template\Twig\Loader\Filesystem.php(139): Twig_Loader_Filesystem->findTemplate('extension/payme...') #1 C:\xampp\htdocs\oczest\upload\system\library\template\Twig\Environment.php(312): Twig_Loader_Filesystem->getCacheKey('extension/payme...') #2 C:\xampp\htdocs\oczest\upload\system\library\template\Twig\Environment.php(378): Twig_Environment->getTemplateClass('extension/payme...', NULL) #3 C:\xampp\htdocs\oczest\upload\system\library\template\twig.php(33): Twig_Environment->loadTemplate('extension/payme...') #4 C:\xampp\htdocs\oczest\upload\system\library\template.php(51): Template\Twig->render('extension/payme...', '0') #5 C:\xampp\htdocs\oczest\upload\system\engine\loader.php(125): Template->render('extension/pa in C:\xampp\htdocs\oczest\upload\system\library\template\Twig\Loader\Filesystem.php on line 215

**Comment by Maverick-com** [comment]
this erroor showing.extension in install but unable to enable......................


Undefined index: token in /home/payu/domains/payufest.in/public_html/admin/controller/extension/payment/pinepg.php on line 135Notice: Undefined index: token in /home/payu/domains/payufest.in/public_html/admin/controller/extension/payment/pinepg.php on line 141Notice: Undefined index: token in /home/payu/domains/payufest.in/public_html/admin/controller/extension/payment/pinepg.php on line 147Notice: Undefined index: token in /home/payu/domains/payufest.in/public_html/admin/controller/extension/payment/pinepg.php on line 151Notice: Undefined index: token in /home/payu/domains/payufest.in/public_html/admin/controller/extension/payment/pinepg.php on line 152
