### ISSUE TITLE
Customers cant register account

### ISSUE THREAD

**Issue by Stevenpreston76** [opencart/opencart#7037]
When customers try to register they get this error:

Fatal error: Uncaught exception 'Exception' with message 'Error: Password not accepted from server!' in /home/lunc2490/public_html/ocart3/system/library/mail/smtp.php:205 Stack trace: #0 /home/lunc2490/public_html/ocart3/system/library/mail.php(142): Mail\Smtp->send() #1 /home/lunc2490/public_html/ocart3/catalog/controller/mail/register.php(44): Mail->send() #2 [internal function]: ControllerMailRegister->index('account/custome...', Array, 6) #3 /home/lunc2490/ocartdata/storage/modification/system/engine/action.php(79): call_user_func_array(Array, Array) #4 /home/lunc2490/public_html/ocart3/system/engine/event.php(62): Action->execute(Object(Registry), Array) #5 /home/lunc2490/ocartdata/storage/modification/system/engine/loader.php(255): Event->trigger('model/account/c...', Array) #6 [internal function]: Loader->{closure}(Array, Array) #7 /home/lunc2490/public_html/ocart3/system/engine/proxy.php(47): call_user_func_array(Object(Closure), Array) #8 /home/lunc2490/public_html/ocart3/catalog/controller/account/register.php(2 in /home/lunc2490/public_html/ocart3/system/library/mail/smtp.php on line 205

**Comment by ADDCreative** [comment]
Your mail settings are probably wrong and it's a question for the forum. https://forum.opencart.com/
