### ISSUE TITLE
Fatel error in customer order list

### ISSUE THREAD

**Issue by Ghyathoo** [opencart/opencart#7740]
**What version of OpenCart are you reporting this for?**
 3.0.3.2
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

My customers can't see them order list when they login to their account the press on order list and they get this
Error message.... 
Fatal error: Uncaught Twig_Error_Syntax: Unexpected "elseif" tag (expecting closing tag for the "for" tag defined near line 34) in "default/template/account/order_list.twig" at line 39. in /system/library/template/Twig/Parser.php:172 Stack trace: #0 /system/library/template/Twig/TokenParser/For.php(40): Twig_Parser->subparse(Array) 
#1 /system/library/template/Twig/Parser.php(187): Twig_TokenParser_For->parse(Object(Twig_Token)). 
#2/system/library/template/Twig/TokenParser/If.php(34): Twig_Parser->subparse(Array)
 #3 /system/library/template/Twig/Parser.php(187): Twig_TokenParser_If->parse(Object(Twig_Token))
 #4/system/library/template/Twig/Parser.php(100): Twig_Parser->subparse(NULL, false) 
#5 /system/library/template/Twig/Environmen in /system/library/template/Twig/Parser.php on line 172

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system... I use one.com hosting 
 - PHP version... Last version 7.4
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]
Firefox last version, Chrome last version, web view android app, xcod ios app
**Additional context**
![Screenshot_20191205_204747](https://user-images.githubusercontent.com/17561921/70260091-9d54ad80-17a0-11ea-993d-0046f9e5397f.jpg)

**Comment by Ghyathoo** [comment]
Problem solved
Extension ( order status color) make this
