### ISSUE TITLE
Error: Variable 'sql_mode' can't be set to the value of 'MYSQL40'

### ISSUE THREAD

**Issue by thewhiterabbit** [opencart/opencart#9118]
**What version of OpenCart are you reporting this for?**
OpenCart Source Archive: https://github.com/opencart/opencart/releases/download/3.0.3.6/opencart-3.0.3.6.zip

**Describe the bug**
!!!This is a fresh install without any database tables!!!

After following the exact instructions in install.txt for linux (including chmod 777), at Step 3 of the installation, the installer fails to write the `config.php` files and produces a blank screen that is addressed at `install/index.php?route=install/step_3`.

On the Pre-Installation page the installer shows all green marks and it seems everything should be fine.

The database tables are created, however, because the `config.php` file does not write, when I change the name of the install directory, I get a 404 because without proper `config.php` files the app falls back to install and it can't find the install directory. If I keep the install directory named correctly it will loop to the same blank Step 3 that I get after clicking "Continue" at Step 3 after dropping all tables in the database and providing the credentials for install.

**To Reproduce**
1. Copy files from "upload" directory to desired sub-directory at domain.
2. Set permissions on all required files to 775 (because they need group execute and write for www-data)
3. Navigate in browser to the sub-directory chosen at step 1.
4. Follow the installer prompts and information.
5. At Step 3 of the installer the result of clicking continue with credentials completed is a blank page.

Log file shows the following error (path amended for privacy):
2021/01/13 18:47:14 [error] 86641#86641: *298 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: Error: Variable 'sql_mode' can't be set to the value of 'MYSQL40'
Error No: 1231
SET @@session.sql_mode = 'MYSQL40' in /var/www/amended_path/opencart/system/library/db/mysqli.php:40

Stack trace:
#0 /var/www/amended_path/opencart/system/library/db.php(45): DB\MySQLi->query()
#1 /var/www/amended_path/opencart/install/model/install/install.php(35): DB->query()
#2 /var/www/amended_path/opencart/system/engine/loader.php(248): ModelInstallInstall->database()
#3 /var/www/amended_path/opencart/system/engine/proxy.php(47): Loader->{closure}()
#4 /var/www/amended_path/opencart/install/controller/install/step_3.php(11): Proxy->__call()
#5 /var/www/amended_path/opencart/system/engine/action.php(79): ControllerInstallStep3->index()
#6 /var/www/amended_path/opencart/system/engine/router.php(67): Action->execute()
#7 /var/www/amended_path/opencart/system/engine/router.php(56): Rout" while reading response header from upstream, client: 104.9.17.32, server: amended.tld, request: "POST amended_path/opencart/install/index.php?route=install/step_3 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "amended.tld", referrer: "https://amended.tld/amended_path/opencart/install/index.php?route=install/step_3"

**Expected behavior**
Normal install completion.

**Server / Test environment (please complete the following information):**
Production Server
Server Details
PHP 7.4.13 (cli) (built: Nov 28 2020 06:24:59) ( NTS )
Zend Engine v3.4.0, with Zend OPcache v7.4.13
Nginx  Version: 1.18.0
Ubuntu 20.04

**Additional context**
I'm hoping to take advantage of the API system to pair this with the MODX CMS for synchronous responsive theming. That's why OpenCart is living in a subdirectory.

**Comment by thewhiterabbit** [comment]
Temporary workaround till core is updated:
Comment out line 35 in opencart/install/model/install/install.php
Comment out line 213 in opencart/install/cli_install.php

Will someone set `session.sql_mode` to the correct mode and pull request please. I'm super busy, and don't have time to do that right now.

**Comment by WebkulOpencart** [comment]
already added the SQL mode, please check the below PR
https://github.com/opencart/opencart/pull/9109

**Comment by mhcwebdesign** [comment]
I am afraid I have to re-open the issue. For OpenCart 3.0.3.7 and MySQL 8 it comes up with the same error:

Error: Variable 'sql_mode' can't be set to the value of 'MYSQL40'

Seriously, is nobody testing the releases anymore?

**Comment by alecgarcia** [comment]
> Removing the offending line in **install/model/install/install.php** seems to resolve it, at least for MySQL 8.
> Can someone please test it out with other MySQL versions, with the `$db->query("SET @@session.sql_mode = 'MYSQL40'");` removed from that file?

This worked for me. Thank you @mhcwebdesign!

**Comment by prabhatkumaroc082** [comment]
This issue is already fixed on maintenance https://github.com/opencart/opencart/tree/3.0.x.x_Maintenance
it should not be faced on 3.0.3.8

**Comment by WebkulOpencart** [comment]
@ismailiiui We have tested this and not found any issue. To allow the zero date we have added this code.

**Comment by oisact** [comment]
I'm also seeing the invalid date `0000-00-00` on a fresh install on a fresh system.

```
PHP Fatal error:  Uncaught Exception: Error: Incorrect DATE value: '0000-00-00'<br />Error No: 1525<br />SELECT DISTINCT *, pd.name AS name, p.image, m.name AS manufacturer, (SELECT price FROM oc_product_discount pd2 WHERE pd2.product_id = p.product_id AND pd2.customer_group_id = '1' AND pd2.quantity = '1' AND ((pd2.date_start = '0000-00-00' OR pd2.date_start < NOW()) AND (pd2.date_end = '0000-00-00' OR pd2.date_end > NOW())) ORDER BY pd2.priority ASC, pd2.price ASC LIMIT 1) AS discount, (SELECT price FROM oc_product_special ps WHERE ps.product_id = p.product_id AND ps.customer_group_id = '1' AND ((ps.date_start = '0000-00-00' OR ps.date_start < NOW()) AND (ps.date_end = '0000-00-00' OR ps.date_end > NOW())) ORDER BY ps.priority ASC, ps.price ASC LIMIT 1) AS special, (SELECT points FROM oc_product_reward pr WHERE pr.product_id = p.product_id AND pr.customer_group_id = '1') AS reward, (SELECT ss.name FROM oc_stock_status ss WHERE ss.stock_status_id = p.stock_status_id AND ss.language_id = '1') AS stock_status, (SELECT wcd.unit  in /var/www/html/system/library/db/mysqli.php on line 41, referer: http://XXX.XXX.XXX.XXX/install/index.php?route=install/step_4

**Comment by mhcwebdesign** [comment]
This has been fixed for both the 4.0.0.0 master branch and the 3.0.3.8 maintenance branch, if you care to read https://github.com/opencart/opencart/issues/9118#issuecomment-826117452

**Comment by mhcwebdesign** [comment]
@oisact: Already fixed, see https://github.com/opencart/opencart/issues/9075#issuecomment-774502931 and https://github.com/opencart/opencart/issues/9004#issuecomment-813333246
