### ISSUE TITLE
BestSeller v3.0.3.2

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#9143]
Version: 3.0.3.2

Code:
```
<h3>{{ heading_title }}</h3>
<div class="row">
 {% for product in products %}
  <div class="product-layout col-lg-3 col-md-3 col-sm-6 col-xs-12">
    <div class="product-thumb transition">
      <div class="image"><a href="{{ product.href }}"><img src="{{ product.thumb }}" alt="{{ product.name }}" title="{{ product.name }}" class="img-responsive" /></a></div>
      <div class="caption">
        <h4><a href="{{ product.href }}">{{ product.name }}</a></h4>
        <p>{{ product.description }}</p>
        {% if product.rating %}
        <div class="rating">
          {% for i in 1..5 %}
          {% if product.rating < i %}
          <span class="fa fa-stack"><i class="fa fa-star-o fa-stack-2x"></i></span>
          {% else %}
          <span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span>
          {% endif %}
          {% endfor %}
        </div>
        {% endif %}
        {% if product.price %}
        <p class="price">
          {% if not product.special %}
          {{ product.price }}
          {% else %}
          {% else %} <span class="price-old">{{ product.price }}</span> <span class="price-new">{{ product.special }}</span> {% endif %}
          {% endif %}
          {% if product.tax %}
          <span class="price-tax">{{ text_tax }} {{ product.tax }}</span>
          {% endif %}
        </p>
        {% endif %}
      </div>
      <div class="button-group">
        <button type="button" onclick="cart.add('{{ product.product_id }}');"><i class="fa fa-shopping-cart"></i> <span class="hidden-xs hidden-sm hidden-md">{{ button_cart }}</span></button>
        <button type="button" data-toggle="tooltip" title="{{ button_wishlist }}" onclick="wishlist.add('{{ product.product_id }}');"><i class="fa fa-heart"></i></button>
        <button type="button" data-toggle="tooltip" title="{{ button_compare }}" onclick="compare.add('{{ product.product_id }}');"><i class="fa fa-exchange"></i></button>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

```

Error:
``Fatal error: Uncaught Twig_Error_Syntax: Unexpected "else" tag (expecting closing tag for the "if" tag defined near line 26) in "default/template/extension/module/bestseller.twig" at line 26. in system/library/template/Twig/Parser.php:172 Stack trace: #0 system/library/template/Twig/TokenParser/If.php(43): Twig_Parser->subparse(Array) #1 system/library/template/Twig/Parser.php(187): Twig_TokenParser_If->parse(Object(Twig_Token)) #2 system/library/template/Twig/TokenParser/If.php(34): Twig_Parser->subparse(Array) #3 system/library/template/Twig/Parser.php(187): Twig_TokenParser_If->parse(Object(Twig_Token)) #4 system/library/template/Twig/TokenParser/For.php(40): Twig_Parser->subparse(Array) #5 system/libra in system/library/template/Twig/Parser.php on line 172`
`

Solution (replace HTML part) from:

```
        {% if product.price %}
        <p class="price">
          {% if not product.special %}
          {{ product.price }}
          {% else %}
          {% else %} <span class="price-old">{{ product.price }}</span> <span class="price-new">{{ product.special }}</span> {% endif %}
          {% endif %}
          {% if product.tax %}
          <span class="price-tax">{{ text_tax }} {{ product.tax }}</span>
          {% endif %}
        </p>
        {% endif %}
```

to

```
        {% if product.price %}
        <p class="price"> {% if not product.special %}
          {{ product.price }}
          {% else %} <span class="price-old">{{ product.price }}</span> <span class="price-new">{{ product.special }}</span> {% endif %}
          {% if product.tax %} <span class="price-tax">{{ text_tax }} {{ product.tax }}</span> {% endif %} </p>
        {% endif %} </div>
```

**Comment by danielkerr** [comment]
is this still in 3.0.3.6? or master branch?

**Comment by faca5** [comment]
Error appear on 3.0.3.2 and 3.0.3.6.

**Comment by faca5** [comment]
You can ignore this.

**Comment by danielkerr** [comment]
if maintenance still has this issue i will leave it open. anyone want to test is maintenance branch has this issue?
