### ISSUE TITLE
pgsql no work Opencart 3

### ISSUE THREAD

**Issue by susl16c** [opencart/opencart#9615]
Warning: pg_query(): Query failed: ОШИБКА: оператор не существует: ` character varying LINE 1: SELECT value FROM oc_setting WHERE `code` = 'config' AND `ke... ^ HINT: Оператор с данным именем и типом аргумента не найден. Возможно, вам следует добавить явное приведение типа. in /var/www/mag/data/www/system/library/db/pgsql.php on line 19Warning: pg_result_error(): supplied resource is not a valid PostgreSQL result resource in /var/www/mag/data/www/system/library/db/pgsql.php on line 47
Fatal error: Uncaught Exception: Error: <br />SELECT value FROM oc_setting WHERE `code` = 'config' AND `key` = 'config_timezone' in /var/www/mag/data/www/system/library/db/pgsql.php:47 Stack trace: #0 /var/www/mag/data/www/storage/modification/system/library/db.php(33): DB\PgSQL->query('SELECT value FR...') #1 /var/www/mag/data/www/system/framework.php(80): DB->__construct('pgsql', 'localhost', '', '', '', '5432') #2 /var/www/mag/data/www/system/startup.php(104): require_once('/var/www/mag/da...') #3 /var/www/mag/data/www//admin/index.php(19): start('admin') #4 {main} thrown in /var/www/mag/data/www/system/library/db/pgsql.php on line 47

**Comment by WebkulOpencart** [comment]
Please mention the OpenCart Version

**Comment by danielkerr** [comment]
Master branch only
