### ISSUE TITLE
Special price page doesnt't work in PHP8

### ISSUE THREAD

**Issue by todavy** [opencart/opencart#9722]
Opencart OpenCart 3.0.3.7

The special price page (https://www.yourdomain.com/index.php?route=product/special) doesn't work (HTTP ERROR 500) in PHP version 8. When I changed to PHP7.4 the page worked.

It sais mimimum requirement is "PHP (at least 5.4) on the Opencart requirements page at:
https://www.opencart.com/index.php?route=cms/download

Good to know -----
There seems to be error messages related with PHP8 and the google advertise/shopping extension in the error log as well
From the error log:
"PHP Unknown:  Required parameter $store_id follows optional parameter $data in [...]/model/extension/advertise/google.php on line 413
PHP Warning:  googleshopping\Googleshopping::integer(): Argument #1 ($product_id) must be passed by reference, value given in [...]/system/library/googleshopping/googleshopping.php on line 583

**Comment by mhcwebdesign** [comment]
Unable to reproduce your error. The OC 3.0.3.7 product/special page works just fine with PHP 8.
Please re-post on the OpenCart forum and provide more details, especially the server's error log entry for your 500 error!

**Comment by TheCartpenter** [comment]
GoogleShopping is no longer supported from the core on anyhow. Better to use an up-to-date version from the Marketplace on opencart.com .

**Comment by todavy** [comment]
Here is the Server Error code for the above event (no errorwhen downgrading to PHP 7.4)
Sun Jun 20 14:12:25.752147 2021] [lsapi:error] [pid 3495101:tid 139675406227200] [client 83.253.14.34:0] [host www.[my account].nu] Backend fatal error: PHP Fatal error:  Uncaught ValueError: Unknown format specifier "r" in /home/[my account]/domains/[my account].nu/public_html/catalog/controller/product/special.php:66\nStack trace:\n#0 /home/[my account]/domains/[my account].nu/public_html/catalog/controller/product/special.php(66): sprintf()\n#1 /home/[my account]/domains/[my account].nu/public_html/system/engine/action.php(79): ControllerProductSpecial->index()\n#2 /home/[my account]/domains/[my account].nu/public_html/catalog/controller/startup/router.php(25): Action->execute()\n#3 /home/[my account]/domains/[my account].nu/public_html/system/engine/action.php(79): ControllerStartupRouter->index()\n#4 /home/[my account]/domains/[my account].nu/public_html/system/engine/router.php(67): Action->execute()\n#5 /home/[my account]/domains/[my account].nu/public_html/system/engine/router.php(56): Router->execute()\n#6 /home/[my account]/domains/[my account].nu/public_html/system/framework.php(169): Router->dispatch()\n#7 /home/[my account]/domains/[my account].nu/public_html/system/startup.php(104): require_once('/home/[my account]/d...')\n#8 /home/[my account]/domains/[my account].nu/public_html/index.php(19): start()\n#9 {main}\n  thrown in /home/[my account]/domains/[my account].nu/public_html/catalog/controller/product/special.php on line 66\n, referer: https://www.[my account].nu/
[Sun Jun 20 14:12:58.268979 2021] [lsapi:error] [pid 3538256:tid 139675330692864] [client 185.189.48.17:0] [host www.[my account].nu] Backend fatal error: PHP Fatal error:  Uncaught ValueError: Unknown format specifier "r" in /home/[my account]/domains/[my account].nu/public_html/catalog/controller/product/special.php:66\nStack trace:\n#0 /home/[my account]/domains/[my account].nu/public_html/catalog/controller/product/special.php(66): sprintf()\n#1 /home/[my account]/domains/[my account].nu/public_html/system/engine/action.php(79): ControllerProductSpecial->index()\n#2 /home/[my account]/domains/[my account].nu/public_html/catalog/controller/startup/router.php(25): Action->execute()\n#3 /home/[my account]/domains/[my account].nu/public_html/system/engine/action.php(79): ControllerStartupRouter->index()\n#4 /home/[my account]/domains/[my account].nu/public_html/system/engine/router.php(67): Action->execute()\n#5 /home/[my account]/domains/[my account].nu/public_html/system/engine/router.php(56): Router->execute()\n#6 /home/[my account]/domains/[my account].nu/public_html/system/framework.php(169): Router->dispatch()\n#7 /home/[my account]/domains/[my account].nu/public_html/system/startup.php(104): require_once('/home/[my account]/d...')\n#8 /home/[my account]/domains/[my account].nu/public_html/index.php(19): start()\n#9 {main}\n  thrown in /home/[my account]/domains/[my account].nu/public_html/catalog/controller/product/special.php on line 66\n

**Comment by todavy** [comment]
Problem solved!

I had mistakenly changed "%s% to %r in the special.php file
$_['text_compare']      = 'Product Compare ([color=red]%r[/color])';
$_['text_compare']      = 'Product Compare (%s)';

Mysterious that it worked oin PHP7.4 and not PHP8 though. It must be more strict language I guess.
